name: riverwise
description: "Apadamitra is a vital multi-platform flood monitoring and safety system, integrating real-time IoT river data, AI-driven flood predictions, and multilingual citizen alerts to keep communities safe and informed."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  firebase_core: '>=2.21.1'
  firebase_auth: '>=5.3.3'
  cloud_firestore: '>=5.5.0'
  firebase_messaging: ^16.0.0
  supabase_flutter: '>=1.10.0'
  google_maps_flutter: ^2.0.0
  geolocator: 13.0.4
  shared_preferences: ^2.0.0
  intl: 0.20.2
  http: ^1.2.1
  flutter_local_notifications: ^19.0.0
  url_launcher: ^6.0.0
  fl_chart: 0.68.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icons/dreamflow_icon.jpg
  remove_alpha_ios: true
